#!/usr/bin/env sh
set -eu

: "${FOCOCONTEXT_BASE_URL:=http://localhost:18080}"
: "${FOCOCONTEXT_API_KEY:?FOCOCONTEXT_API_KEY is required.}"
: "${FOCOCONTEXT_DOCUMENT_PATH:?FOCOCONTEXT_DOCUMENT_PATH is required. Set it to a real local document path.}"

api_base="${FOCOCONTEXT_BASE_URL%/}/v1"

require_json_value() {
  field="$1"
  response="$2"

  value="$(printf '%s' "$response" | jq -er "$field")" || {
    printf 'Quickstart request did not return %s.\n' "$field" >&2
    printf '%s\n' "$response" >&2
    exit 1
  }

  printf '%s' "$value"
}

echo "Creating Knowledge Base..."
kb_response="$(
  curl -sS "$api_base/knowledge-bases" \
    -H "Authorization: Bearer $FOCOCONTEXT_API_KEY" \
    -H "Content-Type: application/json" \
    -d '{"name":"Quickstart Knowledge","template":"team_knowledge","output_language":"en-US"}'
)"
printf '%s\n' "$kb_response"
kb_id="$(require_json_value '.data.id' "$kb_response")"

echo "Uploading source..."
upload_response="$(
  curl -sS "$api_base/knowledge-bases/$kb_id/documents" \
    -H "Authorization: Bearer $FOCOCONTEXT_API_KEY" \
    -H "Idempotency-Key: quickstart-source-001" \
    -F "file=@$FOCOCONTEXT_DOCUMENT_PATH" \
    -F 'data={"display_name":"Quickstart source","source_path":"quickstart/source"}'
)"
printf '%s\n' "$upload_response"
job_id="$(require_json_value '.data.resources.job_id' "$upload_response")"
document_id="$(require_json_value '.data.resources.source_document_id' "$upload_response")"

echo "Checking batch job status..."
curl -sS "$api_base/jobs/batch" \
  -H "Authorization: Bearer $FOCOCONTEXT_API_KEY" \
  -H "Content-Type: application/json" \
  -d "{\"job_ids\":[\"$job_id\"]}"

echo
echo "Checking Knowledge Base ingest progress..."
curl -sS "$api_base/knowledge-bases/$kb_id/ingest-progress" \
  -H "Authorization: Bearer $FOCOCONTEXT_API_KEY"

echo
echo "Running Retrieve..."
retrieve_response="$(
  curl -sS "$api_base/knowledge-bases/$kb_id/retrieve" \
    -H "Authorization: Bearer $FOCOCONTEXT_API_KEY" \
    -H "Content-Type: application/json" \
    -d '{"query":"What are the key platform capabilities?","mode":"hybrid","include_context_pack":true,"include_graph":true,"include_expand_hints":true,"include_resolved_evidence":true}'
)"
printf '%s\n' "$retrieve_response"
require_json_value '.data.knowledge_base_id' "$retrieve_response" >/dev/null
seed_page_id="$(printf '%s' "$retrieve_response" | jq -r '.data.results[0].page_id // empty')"

if [ -n "$seed_page_id" ]; then
  echo "Running Retrieve Expand..."
  curl -sS "$api_base/knowledge-bases/$kb_id/retrieve/expand" \
    -H "Authorization: Bearer $FOCOCONTEXT_API_KEY" \
    -H "Content-Type: application/json" \
    -d "{\"seed_page_ids\":[\"$seed_page_id\"],\"depth\":1,\"include_context_pack\":true,\"include_resolved_evidence\":true}"
fi

echo
echo "Uploaded document ID: $document_id"

if [ -n "${FOCOCONTEXT_FORK_OWNER_ID:-}" ]; then
  echo
  echo "Resolving fork..."
  fork_response="$(
    curl -sS "$api_base/knowledge-bases/$kb_id/forks/resolve" \
      -H "Authorization: Bearer $FOCOCONTEXT_API_KEY" \
      -H "Content-Type: application/json" \
      -d "{\"owner_type\":\"user\",\"external_owner_id\":\"$FOCOCONTEXT_FORK_OWNER_ID\",\"display_name\":\"Quickstart fork user\"}"
  )"
  printf '%s\n' "$fork_response"
  fork_id="$(require_json_value '.data.fork.id' "$fork_response")"

  echo "Submitting fork-owned content..."
  submission_response="$(
    curl -sS "$api_base/forks/$fork_id/submissions" \
      -H "Authorization: Bearer $FOCOCONTEXT_API_KEY" \
      -H "Content-Type: application/json" \
      -H "Idempotency-Key: quickstart-fork-submission-001" \
      -d '{"title":"User-owned platform evidence","content_type":"markdown","content":"## User-owned platform evidence\n\nThis fork-owned note was generated by the developer application and should stay isolated to this fork.","source_url":"https://example.com/fococontext-quickstart-note","evidence":[{"title":"Quickstart note","source_type":"external","url":"https://example.com/fococontext-quickstart-note"}],"citations":[{"label":"Quickstart note","url":"https://example.com/fococontext-quickstart-note"}],"metadata":{"quickstart":true}}'
  )"
  printf '%s\n' "$submission_response"
  submission_job_id="$(require_json_value '.data.job.id' "$submission_response")"

  echo "Polling fork submission job..."
  curl -sS "$api_base/jobs/$submission_job_id" \
    -H "Authorization: Bearer $FOCOCONTEXT_API_KEY"

  echo
  echo "Retrieving from fork..."
  curl -sS "$api_base/knowledge-bases/$fork_id/retrieve" \
    -H "Authorization: Bearer $FOCOCONTEXT_API_KEY" \
    -H "Content-Type: application/json" \
    -d '{"query":"What user-owned platform evidence was submitted?","mode":"hybrid","include_context_pack":true,"include_graph":true}'
fi
