import { readFile } from "node:fs/promises";
import { basename } from "node:path";

import {
  createFococontextClient,
  type RetrieveExpandResponse,
  type UploadSourceDocumentInput,
} from "@fococontext/sdk-js";

interface KnowledgeBase {
  id: string;
}

interface ForkResolveResult {
  fork: {
    id: string;
  };
}

interface ForkSubmission {
  fork_id: string;
  job: {
    id: string;
    status: string;
  };
}

const baseUrl = readRequiredEnv("FOCOCONTEXT_BASE_URL").replace(/\/$/, "");
const apiKey = readRequiredEnv("FOCOCONTEXT_API_KEY");
const client = createFococontextClient({ apiKey, baseUrl });
const documentPath = readRequiredEnv("FOCOCONTEXT_DOCUMENT_PATH");
const forkOwnerId = process.env.FOCOCONTEXT_FORK_OWNER_ID;

const knowledgeBase = await client.createKnowledgeBase<KnowledgeBase>({
  name: "SDK Ready Quickstart",
  template: "team_knowledge",
  output_language: "en-US",
});

const uploadResult = await uploadDocument(knowledgeBase.id, documentPath);
const upload = uploadResult.uploads[0];
if (upload === undefined) {
  throw new Error("Document upload helper returned no uploads.");
}
const job = uploadResult.jobs[0]?.job ?? upload.job;
const retrieval = await client.retrieveKnowledgeContextWithEvidence(knowledgeBase.id, {
  context_pack: { enabled: true },
  context_budget_tokens: 4000,
  graph: { enabled: true, depth: 1 },
  include_trace: true,
  mode: "hybrid",
  query: "What are the key platform capabilities?",
});
const mediaEvidenceCount = retrieval.results.reduce(
  (total, result) =>
    total + (Array.isArray(result.media_evidence) ? result.media_evidence.length : 0),
  0,
);
const seedPageIds = retrieval.results
  .map((result) => (typeof result.page_id === "string" ? result.page_id : null))
  .filter((pageId): pageId is string => pageId !== null)
  .slice(0, 3);
const expansion =
  seedPageIds.length === 0
    ? null
    : await client.expandRetrievedGraphContextWithEvidence<RetrieveExpandResponse>(
        knowledgeBase.id,
        {
          depth: 1,
          include_context_pack: true,
          seed_page_ids: seedPageIds,
        },
      );
const forkSubmission =
  forkOwnerId === undefined || forkOwnerId.trim().length === 0
    ? null
    : await runForkSubmission(knowledgeBase.id, forkOwnerId.trim());

console.log(
  JSON.stringify(
    {
      document_id: upload.resources.source_document_id,
      expand_result_count: expansion?.expanded_results?.length ?? 0,
      failed_job_count: uploadResult.failedJobs.length,
      ingest_progress: {
        overall_progress: uploadResult.progress.overall_progress,
        retrieve_ready: uploadResult.progress.retrieve_ready,
      },
      job_id: job?.id ?? upload.resources.job_id,
      job_status: job?.status ?? upload.job.status,
      knowledge_base_id: knowledgeBase.id,
      media_evidence_count: mediaEvidenceCount,
      next_action_links: upload.links.map((link) => link.rel),
      request_ids: uploadResult.requestIds,
      resolved_evidence_count: retrieval.resolved_evidence?.items.length ?? 0,
      fork_id: forkSubmission?.forkId ?? null,
      fork_submission_job_id: forkSubmission?.submission.job.id ?? null,
      fork_submission_job_status: forkSubmission?.submission.job.status ?? null,
      retrieve_result_count: retrieval.results.length,
      retrieve_target_type: retrieval.target_knowledge_base_type,
      context_budget_strategy: retrieval.context_budget?.strategy_version ?? null,
    },
    null,
    2,
  ),
);

async function runForkSubmission(knowledgeBaseId: string, ownerId: string) {
  const fork = await client.resolveKnowledgeBaseFork<ForkResolveResult>(knowledgeBaseId, {
    display_name: "SDK quickstart fork user",
    external_owner_id: ownerId,
    owner_type: "user",
  });
  const submission = await client.submitForkKnowledge<ForkSubmission>(fork.fork.id, {
    citations: [
      {
        label: "Quickstart note",
        url: "https://example.com/fococontext-quickstart-note",
      },
    ],
    content:
      "## User-owned platform evidence\n\nThis fork-owned note was generated by the developer application and should stay isolated to this fork.",
    content_type: "markdown",
    evidence: [
      {
        source_type: "external",
        title: "Quickstart note",
        url: "https://example.com/fococontext-quickstart-note",
      },
    ],
    metadata: {
      quickstart: true,
    },
    source_url: "https://example.com/fococontext-quickstart-note",
    title: "User-owned platform evidence",
  });
  const forkRetrieval = await client.retrieveKnowledgeContext(fork.fork.id, {
    context_pack: { enabled: true },
    mode: "hybrid",
    query: "What user-owned platform evidence was submitted?",
  });

  return {
    forkId: fork.fork.id,
    forkRetrieveTargetType: forkRetrieval.target_knowledge_base_type,
    submission,
  };
}

async function uploadDocument(knowledgeBaseId: string, path: string) {
  const fileBytes = await readFile(path);
  const file = new File([fileBytes], basename(path));

  return client.uploadSourceDocumentsAndWait(knowledgeBaseId, {
    documents: [
      {
        file,
        name: basename(path),
        sourcePath: "quickstart/source",
      } satisfies UploadSourceDocumentInput,
    ],
    idempotencyKey: "sdk-ready-quickstart-source-001",
    pollIntervalMs: 1000,
    timeoutMs: 120_000,
  });
}

function readRequiredEnv(key: string): string {
  const value = process.env[key];

  if (value === undefined || value.trim().length === 0) {
    throw new Error(`${key} is required.`);
  }

  return value;
}
